[package]
name = "silicate"
version = "1.1.0"
edition = "2024"
description = "A simplistic password manager, built in Rust."
license = "MIT"
repository = "https://github.com/pure-sagacity/silicate"
readme = "README.md"
keywords = ["password", "manager", "cli", "tool", "encryption"]

[[bin]]
name = "silicate"
path = "./src/main.rs"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
clap = { version = "4.0.32", features = ["derive"] }
silicate-core = { path = "../core" }
serde_json = "1.0.96"
crossterm = "0.29.0"
rpassword = "7.5.4"
ratatui = "0.30.2"
chrono = "0.4.45"
arboard = "3.6.1"
colored = "3.1.1"
hex = "0.4.3"
